### ISSUE TITLE
FunctionClauseError in ExDoc.Autolink.walk/2

### ISSUE THREAD

**Issue by bigardone** [elixir-lang/ex_doc#1222] opened 2020-07-17 12:17 UTC
👋 I have upgraded to version `0.22.1` and I'm getting the following error:

```
** (FunctionClauseError) no function clause matching in ExDoc.Autolink.walk/2

    The following arguments were given to ExDoc.Autolink.walk/2:

        # 1
        {"p", [], ["Returns a user by id"], %{}}

        # 2
        %ExDoc.Autolink{app: :my_app, current_module: MyApp.Api.Users, ext: ".html", extras: ["README.md"], file: "lib/my_app/api/users.ex", id: "MyApp.Api.Users.get/4", line: 14, module_id: "MyApp.Api.Users", skip_undefined_reference_warnings_on: []}

    Attempted function clauses (showing 6 out of 6):

        defp walk(list, config) when is_list(list)
        defp walk(binary, _) when is_binary(binary)
        defp walk({:pre, _, _} = ast, _config)
        defp walk({:a, attrs, inner} = ast, config)
        defp walk({:code, attrs, [code]} = ast, config)
        defp walk({tag, attrs, ast}, config)

    (ex_doc 0.22.1) lib/ex_doc/autolink.ex:50: ExDoc.Autolink.walk/2
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ex_doc 0.22.1) lib/ex_doc/formatter/html.ex:118: ExDoc.Formatter.HTML.autolink_and_render/3
    (ex_doc 0.22.1) lib/ex_doc/formatter/html.ex:107: ExDoc.Formatter.HTML.render_doc/3
    (ex_doc 0.22.1) lib/ex_doc/formatter/html.ex:87: anonymous fn/5 in ExDoc.Formatter.HTML.render_all/4
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc 0.22.1) lib/ex_doc/formatter/html.ex:82: anonymous fn/4 in ExDoc.Formatter.HTML.render_all/4
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
```

The documentation generation it's been working for months until now, any idea of what is going on? 
Thank you very much in advance.

**Comment by wojtekmach** [comment] 2020-07-17 12:21
Could you also run `mix deps.update earmark` and try again?

**Comment by wojtekmach** [comment] 2020-07-17 12:30
Actually it might be the other way around, if you also upgraded earmark try to revert _that_ change.

**Comment by wojtekmach** [comment] 2020-07-19 09:44
I tried latest stable ex_doc and earmark and couldn't reproduce this. If you tried the steps mentioned above and still experience the bug, please post the exact version of earmark you are using and the doc that triggers the bug (documentation for `"MyApp.Api.Users.get/4`).

In any case, I believe this is already fixed on master anyway.

**Closed by wojtekmach** 2020-07-19 09:44 UTC

**Comment by bigardone** [comment] 2020-07-20 06:43
@wojtekmach I updated `earmark` and the issue persists :(

**Comment by bigardone** [comment] 2020-07-20 06:47
These are the installed deps BTW:

```
  earmark 1.4.10
  earmark_parser 1.4.10
  ex_doc 0.22.1
  makeup 1.0.3
  makeup_elixir 0.14.1
  mime 1.3.1
  nimble_parsec 0.6.0
```

**Comment by bigardone** [comment] 2020-07-20 06:50
Downgrading back to `0.21.3` makes it work again.

**Comment by wojtekmach** [comment] 2020-07-20 07:37
Could you paste the piece of documentation that was causing the crash?

**Comment by bigardone** [comment] 2020-07-20 08:11
Sure!

```
  @doc """
  Returns a user by id
  Returns a user

  ## Parameters

  - connection (MyApp.Connection): Connection to server
  - id (String.t): User ID
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, status, %MyApp.User{}} on success
  {:error, info} on failure
  """
```

Here's the error after the upgrade:

```
** (FunctionClauseError) no function clause matching in ExDoc.Autolink.walk/2

    The following arguments were given to ExDoc.Autolink.walk/2:

        # 1
        {"p", [], ["Returns a user by id\nReturns a user"], %{}}

        # 2
        %ExDoc.Autolink{app: :my_app, current_module: MyApp.Api.Users, ext: ".html", extras: ["README.md"], file: "lib/my_app/api/users.ex", id: "MyApp.Api.Users.fetch_asset_by_company_id_and_id/4", line: 14, module_id: "MyApp.Api.Users", skip_undefined_reference_warnings_on: []}

    Attempted function clauses (showing 6 out of 6):

        defp walk(list, config) when is_list(list)
        defp walk(binary, _) when is_binary(binary)
        defp walk({:pre, _, _} = ast, _config)
        defp walk({:a, attrs, inner} = ast, config)
        defp walk({:code, attrs, [code]} = ast, config)
        defp walk({tag, attrs, ast}, config)

    (ex_doc 0.22.1) lib/ex_doc/autolink.ex:50: ExDoc.Autolink.walk/2
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ex_doc 0.22.1) lib/ex_doc/formatter/html.ex:118: ExDoc.Formatter.HTML.autolink_and_render/3
    (ex_doc 0.22.1) lib/ex_doc/formatter/html.ex:107: ExDoc.Formatter.HTML.render_doc/3
    (ex_doc 0.22.1) lib/ex_doc/formatter/html.ex:87: anonymous fn/5 in ExDoc.Formatter.HTML.render_all/4
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc 0.22.1) lib/ex_doc/formatter/html.ex:82: anonymous fn/4 in ExDoc.Formatter.HTML.render_all/4
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
```

**Comment by wojtekmach** [comment] 2020-07-20 08:37
Thank you @bigardone, there was a bug in ExDoc after all, the fix will be in the next release. Earmark started warning on this particular markdown and we were incorrectly handling that warning. You could work around it by updating your docs:

```diff
  ## Returns

-  {:ok, status, %MyApp.User{}} on success
-  {:error, info} on failure
+  `{:ok, status, %MyApp.User{}}` on success
+  `{:error, info}` on failure
```

**Comment by bigardone** [comment] 2020-07-20 08:46
🎉 No problem! Thank you for putting time into it 🙌
