### ISSUE TITLE
char "f" do not show for some words

### ISSUE THREAD

**Issue by Tica2** [elixir-lang/ex_doc#511] opened 2016-01-23 16:58 UTC
on ecto docs:
https://hexdocs.pm/ecto/Ecto.Schema.html#has_many/3
paragraf:
`:through - If this association must be deined`  
I reed  `deined` instead `defined`

Tests on Mac OS Firefox + Safari
Picture here:
https://drive.google.com/file/d/0B0ERMrTdlpURQ3ZlZmRaY0paVzg/view?pref=2&pli=1

Good to use font that do not have this problem.

Thanks!

**Comment by josevalim** [comment] 2016-01-23 17:28
We just need to add this to the body CSS:

    -webkit-font-variant-ligatures: no-common-ligatures;

@Dignifiedquire, do you agree?

**Comment by Dignifiedquire** [comment] 2016-01-23 19:11
This is really odd. For me it looks completely fine (OS X)

### Firefox
![screen shot 2016-01-23 at 20 10 09](https://cloud.githubusercontent.com/assets/790842/12532173/5d6533d0-c20d-11e5-9dff-b981bb8eff23.png)


### Safari

![screen shot 2016-01-23 at 20 11 07](https://cloud.githubusercontent.com/assets/790842/12532177/76d82f52-c20d-11e5-8cda-6d2a8ab88070.png)

**Comment by josevalim** [comment] 2016-01-23 19:14
What is your safari version? Mine is: Version 9.0.2 (10601.3.9)

Maybe ligatures are a fairly new feature. I am also on Mavericks but I can confirm the issue exists here.

**Comment by Dignifiedquire** [comment] 2016-01-23 19:17
@josevalim mine is even newer: Version 9.0.2 (11601.3.9) maybe it's fixed in that build?

**Comment by josevalim** [comment] 2016-01-23 19:31
Isn't yours the same as mine? :P

**Comment by josevalim** [comment] 2016-01-23 19:32
@Tica2 @Dignifiedquire which OS are you on?

**Comment by Tica2** [comment] 2016-01-23 20:12
El Capitan 10.11.2 (15C50)

**Comment by Tica2** [comment] 2016-01-23 20:13
Firefox 43.0.4, 
Safari Version 9.0.2 (11601.3.9)

**Comment by josevalim** [comment] 2016-01-23 22:12
I will go ahead because Safari is definitely trying to use ligatures here and the font does not support ligatures, so I don't see any occasions where the instruction above would be harmful. :)

**Comment by Dignifiedquire** [comment] 2016-01-23 22:27
Sure go ahead, but are you sure a `webkit` prefix will change anything in Firefox?

**Comment by josevalim** [comment] 2016-01-23 22:32
I can't reproduce it in Firefox. But if someone can give it a try and find
the proper one, I am all ears :D

On Saturday, January 23, 2016, Friedel Ziegelmayer <notifications@github.com>
wrote:

> Sure go ahead, but are you sure a webkit prefix will change anything in
> Firefox?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ex_doc/issues/511#issuecomment-174227194>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by sheharyarn** [comment] 2016-01-24 00:48
I can confirm the issue exists. Tested on Firefox, Safari and Chrome but the Fs are only invisible in Firefox and Safari. I'm on an Macbook Air running OSX El Capitan 10.11.2.


![screen shot 2016-01-24 at 5 45 14 am](https://cloud.githubusercontent.com/assets/2355108/12533784/ee82b7d4-c25d-11e5-92bd-4f706530b656.png)

_Notice the 'defines' in the second paragraph_

**Comment by sheharyarn** [comment] 2016-01-24 05:46
Sent in a pull req that fixes this.

**Closed** 2016-01-24 08:50 UTC

**Comment by josevalim** [comment] 2016-01-24 09:35
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment] 2016-01-24 09:35
0.11.4 is out.

**Comment by josevalim** [comment] 2016-01-25 19:44
The root cause was found: https://github.com/Automattic/wp-calypso/issues/2720 :)

**Comment by Tica2** [comment] 2016-01-25 19:47
:+1: good

**Comment by davelab6** [comment] 2016-01-27 13:20
This should now be totally fixed at the GF API side :)

**Comment by josevalim** [comment] 2016-01-27 13:21
I will revert the css changes then, thank you @davelab6.

**Comment by Dignifiedquire** [comment] 2016-01-27 14:15
> fixed at the GF API side

I just read "fixed at the girl friend API side" and was super confused :laughing:

**Comment by davelab6** [comment] 2016-01-27 16:44
My girlfriend regular refers to Google Fonts as my other girlfriend due to workaholism =)
