### ISSUE TITLE
Bullet list not displayed correctly

### ISSUE THREAD

**Issue by williamthome** [elixir-lang/ex_doc#1911] opened 2024-06-03 13:41 UTC
In the [README.md](https://github.com/williamthome/doctest?tab=readme-ov-file#overview):
![image](https://github.com/elixir-lang/ex_doc/assets/35941533/4be4c468-3c22-4ae6-b982-2993f9c99fa4)

How it is displayed in [hex](https://hexdocs.pm/doctest/0.9.0/readme.html#overview):
![image](https://github.com/elixir-lang/ex_doc/assets/35941533/76d6eeae-5d8f-48f4-afe0-6addf1719935)

**Comment by wojtekmach** [comment] 2024-06-03 13:52
When trying this out in my project I got a warning,

```
    warning: Fenced Code Block opened with ``` not closed at end of input
    │
 78 │ ```elixir
    │ ~~~~~~~~~
    │
    └─ README.md:78: (file)
```

which I fixed by changing:

`````diff
- ```erlang
+ ````erlang
  %% @doc Prints "Hello, Joe!"
  %% Example:
  %% ```
  %% 1> print().
  %% "Hello, Joe!"
  %% '''
  print() -> "Hello, Joe!".
- ```
+ ````
`````

since there was a conflicting ` ``` ` inside. The warning did not point out the exact problem and it will probably be tough to improve it but enhancements to the markdown library we use, earmark, are always welcome.

**Closed by wojtekmach** 2024-06-03 13:52 UTC

**Comment by garazdawi** [comment] 2024-06-03 13:58
I would say that the problem is that earmark (incorrectly) sees the ````%% ``` ```` line as a closing of the fenced code block. The only thing that should be allowed before a closing fenced code block is whitespaces.

**Comment by williamthome** [comment] 2024-06-03 14:11
Good catch. Thank you!

**Comment by williamthome** [comment] 2024-06-03 14:21
I think the problem is that I generate the docs by running `rebar3 hex build`:
```
$ rebar3 hex build
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling doctest
Your package tarball is available at /home/williamthome/Projects/williamthome/doctest/_build/default/lib/doctest/hex/doctest-0.9.0.tar
===> Analyzing applications...
===> Compiling doctest
===> Running edoc for doctest
===> Running ex_doc for doctest
Your docs tarball is available at /home/williamthome/Projects/williamthome/doctest/_build/default/lib/doctest/hex/doctest-0.9.0-docs.tar
```
No warning is emitted.
