### ISSUE TITLE
Named type isn't linked when there's a type variable with the same name

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/ex_doc#630] opened 2016-10-29 14:00 UTC
When there's a type defined in the current module, and a function has a spec that uses the same name as the type for one of its type variables, the type in the spec isn't linked to the type definition.

For example, create a new Mix project and bring in ExDoc from master, then have this in a module:

``` elixir
defmodule ExDocBug do
  @type foo :: atom

  @spec hello(foo) :: :ok when foo: foo
  def hello(foo), do: :ok

  @spec world(bar) :: :ok when bar: foo
  def world(bar), do: :ok
end
```

Now run `mix docs` and go to the documentation: you will see that the `foo/0` type is linked from the spec of the `world/1` function but not from the spec of the `hello/1` function.

<img width="327" alt="screen shot 2016-10-29 at 3 59 20 pm" src="https://cloud.githubusercontent.com/assets/3890250/19830067/af88359e-9df0-11e6-9a47-985ef820be8c.png">

\cc @lexmag

**Comment by josevalim** [comment] 2016-10-29 19:01
@whatyouhide @lexmag this may be a bug in Elixir if the AST for `when foo: foo` has foo as a variable rather than a funcall.

**Comment by whatyouhide** [comment] 2016-10-29 19:59
Oh, I see. I will investigate when I have some time 👍

**Comment by ivanovaleksey** [comment] 2017-08-18 21:44
Hi guys, looks like the issue is still here.
I tried to inspect AST with placing `IO.inspect` in the snippet.
```
IO.inspect (quote do: (@spec hello(foo) :: :ok when foo: foo))
```
it gives me
```
{:@, [context: ExDocBug, import: Kernel],
[{:spec, [context: ExDocBug],
  [{:when, [],
    [{:::, [], [{:hello, [], [{:foo, [], ExDocBug}]}, :ok]},
     [foo: {:foo, [], ExDocBug}]]}]}]}
```

I don't all AST meanings yet.
@josevalim does `[foo: {:foo, [], ExDocBug}]` mean that `foo` is treated like a local variable, like you suppose?

By the way, what is the idea behind using guard in type specification and not in the code itself?

**Comment by wojtekmach** [comment] 2017-12-16 17:48
Worth noting that changing:

```elixir
  @spec hello(foo) :: :ok when foo: foo
  def hello(foo), do: :ok
```

to:

```elixir
  @spec hello(foo) :: :ok when foo: foo()
  def hello(foo), do: :ok
```

makes it autolink properly.

So I think if we can make it that `bar` in `:: when foo: bar` will be represented as `{:bar, [], []}` (as opposed to `{:bar, [], Elixir}` as today) this will be automatically fixed on ex_doc side as it operates on AST for typespecs.

**Comment by josevalim** [comment] 2019-01-21 09:59
@whatyouhide you need to add parens otherwise you are referring to the variable itself. For example:

```elixir
defmodule ExDocBug do
  @spec hello(foo) :: :ok when foo: foo
  def hello(foo), do: :ok
end
```

compiles because you are defining `foo` recursively. But this doesn't, because you are effectively using the type:

```elixir
defmodule ExDocBug do
  @spec hello(foo) :: :ok when foo: foo()
  def hello(foo), do: :ok
end
```

So ExDoc is correct in not highlighting it.

**Closed by josevalim** 2019-01-21 09:59 UTC
Labels: Kind:Bug
