### ISSUE TITLE
Back button doesn't bring you back to search results page

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ex_doc#513] opened 2016-01-27 14:47 UTC
If you click a link from the search results page and then use the browser back button it wont bring you back to the search results.

**Comment by bcardarella** [comment] 2016-03-01 10:47
The search page is currently a modal. I suspect it would be non-trivial to properly manage the application history state unless a history and route manager for javascript.

**Comment by allyraza** [comment] 2016-03-07 09:34
We can use can push state when user clicks on a link to fix this, but it won't work in older browser I can send PR if that's okay

**Comment by josevalim** [comment] 2016-03-07 10:54
I believe that's fine. It is for developers, we at least expect them to
have up to date browsers. :)

On Monday, March 7, 2016, Ally Raza <notifications@github.com> wrote:

> We can use can push state when user clicks on a link to fix this, but it
> won't work in older browser I can send PR if that's okay
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ex_doc/issues/513#issuecomment-193180258>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment] 2016-10-08 15:39
Duplicate of #341.

**Closed by josevalim** 2016-10-08 15:39 UTC
Labels: Area:Design, Kind:Enhancement
