### ISSUE TITLE
Wrong HTML generation

### ISSUE THREAD

**Issue by mfbmina** [elixir-lang/ex_doc#1292] opened 2020-11-24 15:47 UTC
Versions: 

- ex_doc: 0.23
- earmarker_parser: 1.4.10

We are generating the following `.md` file:

```
# Available features

## Caveats

### *Products* column

1. Text 1
2. Text 2

<table>
  <thead>
    <tr>
      <th>Feature ID</th>
      <th>Type</th>
      <th>Products</th>
    </tr>
  </thead>
</table>
```

Which is being converted to the following `HTML` file (I'm ommitting not relevant HTML code):

```
<section class="content">
  <div class="content-outer">
    <div id="content" class="content-inner">

<h1>Available features</h1><h2 id="caveats" class="section-heading">
  <a href="#caveats" class="hover-link"><span class="icon-link" aria-hidden="true"></span></a>
  Caveats
</h2>
<h3 id="products-column" class="section-heading">
  <a href="#products-column" class="hover-link"><span class="icon-link" aria-hidden="true"></span></a>
  <em>Products</em> column
</h3>
<ol><li>Text 1</li><li>Text 2</li></ol><table>  &lt;thead&gt;    &lt;tr&gt;      &lt;th&gt;Feature ID&lt;/th&gt;      &lt;th&gt;Type&lt;/th&gt;      &lt;th&gt;Products&lt;/th&gt;    &lt;/tr&gt;  &lt;/thead&gt;</table> 
```

The table is broken because of this and I'm not sure how to fix it. 

PS: I'm not sure if here is the right place to open this issue

**Comment by wojtekmach** [comment] 2020-11-24 16:21
Thank you for the report (yup, this is the place to open the issue!)

This is a regression caused by internal changes we've been making preparing for future features, we don't yet have a fix. Here's a similar issue: https://github.com/elixir-lang/ex_doc/issues/1189.

If you need to embed html in your markdown it's probably best to downgrade to ExDoc v0.21.x.

**Comment by mfbmina** [comment] 2020-11-25 09:16
Thanks ❤️

**Comment by josevalim** [comment] 2020-12-09 08:12
Closing in favor of #1189.

**Closed by josevalim** 2020-12-09 08:12 UTC
