### ISSUE TITLE
Elixir.module_info/1 is undefined (module Elixir is not available)

### ISSUE THREAD

**Issue by davydog187** [elixir-lang/ex_doc#1149] opened 2020-04-18 22:25 UTC
While working on #1148, I noticed that the current master of `ex_doc` is broken when running against Elixir (both master and 1.10.2).

```
~/Development/elixir [tags/v1.10.2] λ make docs
==> ex_doc (elixir)
bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.10.2" "lib/elixir/ebin" --main "Kernel" --source-url "https://github.com/elixir-lang/elixir" --source-ref "v1.10.2"  --output doc/elixir --canonical "https://hexdocs.pm/elixir/v1.10/ " --homepage-url "https://elixir-lang.org/docs.html" --formatter "html" --config "lib/elixir/docs.exs"
** (UndefinedFunctionError) function Elixir.module_info/1 is undefined (module Elixir is not available)
    Elixir.module_info(:exports)
    (ex_doc 0.22.0-dev) lib/ex_doc/refs.ex:92: ExDoc.Refs.from_chunk/2
    (ex_doc 0.22.0-dev) lib/ex_doc/refs.ex:52: ExDoc.Refs.public?/1
    (ex_doc 0.22.0-dev) lib/ex_doc/autolink.ex:340: ExDoc.Autolink.module_url/2
    (ex_doc 0.22.0-dev) lib/ex_doc/autolink.ex:63: ExDoc.Autolink.walk/2
    (elixir 1.10.2) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.10.2) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ex_doc 0.22.0-dev) lib/ex_doc/autolink.ex:71: ExDoc.Autolink.walk/2
make: *** [docs_elixir] Error 1
```

I got around it by changing this line to an empty list `[]` https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/refs.ex#L109

I'm happy to fix this bug if someone can point me in the right direction.

**Comment by IvanRublev** [comment] 2020-04-19 08:35
Same for me. With ex_doc v0.21.3 it works.
@wojtekmach looks like the new autolinker breaks documentation generation for Elixir.

**Comment by wojtekmach** [comment] 2020-04-19 09:23
Thank you both for the report. I couldn't reproduce it. Could you paste your `elixir --version`? In particular, I'd like to know your OTP version.

> `Elixir.module_info(:exports)`
> I got around it by changing this line to an empty list []

the root cause is we should never do anything on the `Elixir` module, this module does not exists. So it incorrectly is being treated as a module to generate docs for by some earlier code. Btw, the `module_info` fallback is for the upcoming Erlang support so we shouldn't remove that ;-)

**Comment by davydog187** [comment] 2020-04-19 10:48
Hi @wojtekmach :wave: 

```
~/Development/elixir [tags/v1.10.2] λ elixir --version
Erlang/OTP 22 [erts-10.5.6] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.10.1 (compiled with Erlang/OTP 22)
```

**Comment by wojtekmach** [comment] 2020-04-19 11:07
I still cannot reproduce this. Could you try the following? Just want to make sure ExDoc was compiled using the same Elixir version you're trying to build docs for (though it shouldn't matter that much)

```
$ cd /path/to/elixir
$ make clean compile
$ (cd ../ex_doc && rm -rf _build deps && mix deps.get && mix compile)
$ make docs
```

**Comment by davydog187** [comment] 2020-04-19 11:32
Same error @wojtekmach 

```
~/Development/elixir [tags/v1.10.2] λ make docs
==> ex_doc (elixir)
bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.10.2" "lib/elixir/ebin" --main "Kernel" --source-url "https://github.com/elixir-lang/elixir" --source-ref "v1.10.2"  --output doc/elixir --canonical "https://hexdocs.pm/elixir/v1.10/ " --homepage-url "https://elixir-lang.org/docs.html" --formatter "html" --config "lib/elixir/docs.exs"
** (UndefinedFunctionError) function Elixir.module_info/1 is undefined (module Elixir is not available)
    Elixir.module_info(:exports)
    (ex_doc 0.22.0-dev) lib/ex_doc/refs.ex:92: ExDoc.Refs.from_chunk/2
    (ex_doc 0.22.0-dev) lib/ex_doc/refs.ex:52: ExDoc.Refs.public?/1
    (ex_doc 0.22.0-dev) lib/ex_doc/autolink.ex:340: ExDoc.Autolink.module_url/2
    (ex_doc 0.22.0-dev) lib/ex_doc/autolink.ex:63: ExDoc.Autolink.walk/2
    (elixir 1.10.2) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.10.2) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ex_doc 0.22.0-dev) lib/ex_doc/autolink.ex:71: ExDoc.Autolink.walk/2
make: *** [docs_elixir] Error 1
```

**Comment by davydog187** [comment] 2020-04-19 11:34
Happy to pair on it with you if you want

**Comment by wojtekmach** [comment] 2020-04-19 11:59
I paired with @davydog187 and what seems to be happening is `Elixir` is marked as a module because there is a corresponding `Elixir.beam` file, except the file is actually `elixir.beam` (lower case) for the private https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir.erl. This bug happens on case insensitive file systems like the default on macOS. I'll take care of this.

Thanks again @davydog187! <3

**Closed** 2020-04-19 14:29 UTC

**Comment by davydog187** [comment] 2020-04-19 21:10
@wojtekmach It still breaks after you fix.

```
17:08:48.287 [error] beam/beam_load.c(1433): Error loading module 'Elixir':
  BEAM file exists but it defines a module named elixir



17:08:48.287 [error] Loading of /Users/dave/Development/elixir/lib/elixir/ebin/Elixir.beam failed: :badfile
```

**Comment by wojtekmach** [comment] 2020-04-19 21:30
Thanks for testing this, I just pushed another fix on master and we should be good for now.
