### ISSUE TITLE
HTML in headers when the header contains an atom

### ISSUE THREAD

**Issue by Gazler** [elixir-lang/ex_doc#587] opened 2016-07-22 10:32 UTC
Looks like atoms inside of headers may cause some issues.

     Git options (<code class="inline">:git</code>)

http://elixir-lang.org/docs/stable/mix/Mix.Tasks.Deps.html#module-git-options-code-class-inline-git-code

**Comment by joshprice** [comment] 2016-07-26 06:25
Good catch, I'll take a look

**Comment by joshprice** [comment] 2016-07-26 06:49
For reference it used to retain that markdown as is (http://elixir-lang.org/docs/v1.2/mix/Mix.Tasks.Deps.html) does it even make sense to retain this behaviour?

**Comment by nscyclone** [comment] 2016-07-26 07:13
I suppose that the result should look like [this](http://i.imgur.com/hoLrSaM.png?1). 
The problem is that HTML entities in headers are escaped. Not sure whether it is caused by the Markdown parser itself.

**Comment by joshprice** [comment] 2016-07-26 16:50
Agreed, that's the intention and it looks ok.

I did make an assumption that extra markup in headers probably wasn't a
great idea in most cases, but mostly because I hadn't seen many examples of
it done.

We could try escaping the HTML, but I wonder what the consequences might be?

**Comment by josevalim** [comment] 2016-07-26 18:18
Agreed with @nscyclone. If that is valid markdown and it renders correctly, I think we should keep such properties (i.e. we should stop escaping the HTML).

**Comment by joshprice** [comment] 2016-07-28 08:09
So tried to remove escaping and it breaks an existing test https://github.com/elixir-lang/ex_doc/blob/e0b99984b7713c52b404b674a630f17d79da0641/test/ex_doc/formatter/html_test.exs#L165

So unless we go back to preprocessing the markdown we're only able to support either escaping html entities or converting markup. I'd imagine that an `&` or `>` in a header might be more likely than HTML markup.

Thoughts?

**Comment by joshprice** [comment] 2016-08-26 13:08
Fixed in https://github.com/elixir-lang/ex_doc/issues/591

**Closed** 2016-08-26 14:47 UTC
Labels: Kind:Bug
