### ISSUE TITLE
Closing "package switcher" with Esc blocks it from opening again

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#1058] opened 2019-07-19 06:26 UTC
Afterwards we can't open "?" etc.

cc @cybrox

**Comment by archdragon** [comment] 2019-07-19 12:30
I've tried to reproduce it (on https://hexdocs.pm/elixir/master/ ), but can't.

Did you take any extra steps between opening the switcher and closing it?

**Comment by wojtekmach** [comment] 2019-07-19 12:41
No, all I'm doing is: <kbd>g</kbd> <kbd>Esc</kbd> <kbd>g</kbd>

But thanks for checking in, I just found out the bug is on Safari but not on Firefox!

**Comment by archdragon** [comment] 2019-07-19 13:14
@cybrox @wojtekmach I think I know what might be the case, since something similar happened to me in autocomplete. Will prepare a quick PR and demo to test this. :)

**Closed** 2019-07-19 13:19 UTC
Labels: Area:JavaScript, Kind:Bug
