### ISSUE TITLE
Rendering regression in 0.22

### ISSUE THREAD

**Issue by imanhodjaev** [elixir-lang/ex_doc#1189] opened 2020-06-15 22:26 UTC
Hey,

In version `0.21` it was rendering markdown with HTML blocks as expected for example the following block 

```html
<h1 align="center">
Bla bla
</h1>
<p align="center">
  <img width="150" height="150" src="https://image.svg"/>
</p>
```

In version 0.22 `ex_doc` renders tags as plain text.

Also parser is unable to properly parse text blocks for example if you put
```html
<h1 align="center">Title</h1>
```
It will render

```html
Title</h1>
```

Elixir version: 1.10.3
earmark: 1.4.5
makeup: 1.0.3
makeup_elixir: 0.14.1

Thanks.

**Comment by josevalim** [comment] 2020-06-16 06:55
Can you please provide a sample project that reproduces the error? Thanks.

**Comment by imanhodjaev** [comment] 2020-06-16 09:33
Hi Jose,

Project documentation is here https://hexdocs.pm/dust/readme.html and GitHub link is https://github.com/imanhodjaev/dust

**Comment by eksperimental** [comment] 2020-06-16 16:47
The generated HTML is fine and it looks fine in my browser.
Did you try with a different browser or with no extensions installed?

**Comment by imanhodjaev** [comment] 2020-06-16 17:37
@eksperimental yes I tried on different browsers also hex docs https://hexdocs.pm/dust/readme.html show the same thing
<img width="869" alt="Screenshot 2020-06-16 at 19 36 26" src="https://user-images.githubusercontent.com/354868/84808282-c506b700-b008-11ea-9535-0beece1b85f9.png">

**Comment by eksperimental** [comment] 2020-06-16 21:47
@imanhodjaev I see what you mean now.
I went head and wrote a test and ran `git bisect` and the commit that introduced the bug is:

```
f553cc0c406ab0b589be652bd4148893c785bd8b is the first bad commit
commit f553cc0c406ab0b589be652bd4148893c785bd8b
Author: Wojtek Mach <wojtek@wojtekmach.pl>
Date:   Thu Mar 5 15:53:42 2020 +0100

    Use new autolinker
    
    * Replace `ExDoc.Markdown.to_html/2` with `to_ast/2`
    * Change the flow from `markdown->autolink->html` to `markdown->ast->autolink->html`
    * Add `:app` to ExDoc configuration (for generating project-local links)
```

/cc @wojtekmach 
I can share the test and the shell script if needed

**Comment by imanhodjaev** [comment] 2020-06-16 21:49
@eksperimental awesome! Thank you very much for your investigation. ✨🚀✨

**Comment by eksperimental** [comment] 2020-06-16 21:56
a reduced case is this
it converts `<h1>Title</h1>` to `Title&lt;/h1&gt;` and inserts this string in the `<title>` and `<h1>` elements

`<p><img src="image.svg"/></p>` to 
to `<p>&lt;img src=&quot;image.svg&quot;/&gt;&lt;/p&gt;</p>`

**Comment by wojtekmach** [comment] 2020-06-16 22:28
Thanks for the report and confirmation. The issue is similar to https://github.com/elixir-lang/ex_doc/issues/1168, we shouldn't escape.

**Comment by eksperimental** [comment] 2020-06-17 00:38
PR submitted #1190

**Comment by josevalim** [comment] 2020-06-17 06:11
Closing in favor of #1190.

**Comment by lexmag** [comment] 2021-01-03 21:14
The regression happens from the EarmarkParser usage:
ExDoc 0.22 started to use Earmark 1.4 (shipped with EarmarkParser),
and now ExDoc directly depends on EarmarkParser.
EarmarkParser has incomplete support for HTML blocks: (https://github.com/RobertDober/earmark_parser/issues/30), and sometimes it could discard content (https://github.com/RobertDober/earmark_parser/issues/31).

**Closed** 2021-01-12 10:25 UTC
Labels: Area:Elixir, Area:HTML, Kind:Bug

**Comment by wojtekmach** [comment] 2021-01-12 10:28
@RobertDober sorry for some of the earmark reports that stemmed from this and similar issues, we were incorrectly handling the Earmark AST. Now we're properly differentiating between verbatim and non-verbatim nodes that pretty much solves the problem!

**Comment by RobertDober** [comment] 2021-01-12 11:37
again no need to apologise I am not really up to speed with these issues, we had been planning to make EarmarkParser more GFM like, as it is becoming quite clear that for many, nowadays `Markdown == GFM`, unfortunately I do not have time, energy and inspiration right now, sorry.

I will of course at least tend to my social duties.

**Comment by josevalim** [comment] 2021-01-12 12:09
Hi @RobertDober!

FWIW, EarmarkParser works *great* for us! And to be clear, I don't think anyone should expect you to make Earmark behave more like GFM. If you would welcome contributions that add those features then you can always say so and hope people will contribute, but you shouldn't really sweat or work on it unless you actually want to. :) 

Have a great week!

**Comment by RobertDober** [comment] 2021-01-12 14:31
Oh I will certainly accept any PR in that direction, but it is a delicate matter ...

Thanx for your kind encourgament and (IIANM) Prospero Ano Novo
