### ISSUE TITLE
`mix test` would not recompile fixtures

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#438] opened 2015-09-26 07:48 UTC
`mix test` would not recompiled fixtures if there is a `.beam` file present in the beam_dir,
basically, if you update your fixtures, and you run `mix text` you won't see the changes.
and `mix compile` won't touch them.
so all you can do is `MIX_ENV=test mix clean`
and recompile the whole ex_doc again,
and if you make a change, you have to recompile everything again.

these are the lines involving this bug.
https://github.com/elixir-lang/ex_doc/blob/master/test/test_helper.exs#L9-L14

my question is,
what's the best way to deal with this?
check the time in the beamfiles and see if they need to be recompiled?
or remove the conditional

**Comment by josevalim** [comment] 2015-09-26 09:45
fixed in master.

**Closed by josevalim** 2015-09-26 09:45 UTC
Labels: Area:Elixir, Kind:Bug

**Comment by eksperimental** [comment] 2015-09-26 10:32
thank you @josevalim, much neater now.
just playing aorund with it, I came up with an issue (probably a Mix issue).

If i delete the a beam file from the ebin folder, without modifying the .ex file.
and i run `mix compile`

the file will be ignored.
I think what it does check is that the file has not changed, but it doesn't take into consideration that the beam files is not present.
let me know if it's a bug, i will submit it to the elixir tracker.

**Comment by josevalim** [comment] 2015-09-26 11:01
It is not a bug because you are not supposed to touch _build.

**Comment by eksperimental** [comment] 2015-09-26 11:11
:grimacing:
