### ISSUE TITLE
Uncaught JS ReferenceError: sidebarNodes is not defined

### ISSUE THREAD

**Issue by njonsson** [elixir-lang/ex_doc#642] opened 2016-11-18 02:48 UTC
This occurs in [_assets/js/events.js_:143](https://github.com/elixir-lang/ex_doc/blob/a02ef545ce1934bb14dcb10274d0871685702cf4/assets/js/events.js#L143). None of the sidebar items are shown. I suspect [_lib/ex_doc/formatter/html/templates.ex_:122](https://github.com/elixir-lang/ex_doc/blob/78adbaff7884bd53fa4bb7d8d34a59c52a9f749b/lib/ex_doc/formatter/html/templates.ex#L122) is never getting executed, but I don’t know why.

This occurs in various browsers, including Safari v9.1, Firefox 49 (MacOS), and Opera 41 (MacOS).

**Comment by milmazz** [comment] 2016-11-18 03:18
@njonsson Where did you see that error? URI? Did you clean your cache first?

**Comment by njonsson** [comment] 2016-11-18 04:14
Yes, I removed _doc/_, ran `mix docs`, cleared my browser cache, and reopened _doc/index.html_. The error recurs.

**Comment by milmazz** [comment] 2016-11-18 05:00
@njonsson Could you please tell me which `ExDoc` version are you using?

I just run the following test with `ExDoc` from the `master` branch:

```console
$ cd ~/Dev/elixir-lang/
$ rm -rf doc
$ make docs_elixir
==> elixir (compile)
==> ex_doc (elixir)
bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.4.0-dev" "lib/elixir/ebin" -m "Kernel" -u "https://github.com/elixir-lang/elixir" --source-ref "1f11071505b0af6b5c6f5293bbb7ada401dab6c5"  -o doc/elixir -n http://elixir-lang.org/docs/master/elixir/ -p http://elixir-lang.org/docs.html -f "html" -e "lib/elixir/pages/Behaviours.md" -e "lib/elixir/pages/Guards.md" -e "lib/elixir/pages/Naming Conventions.md" -e "lib/elixir/pages/Operators.md" -e "lib/elixir/pages/Typespecs.md" -e "lib/elixir/pages/Writing Documentation.md"
$ open doc/elixir/index.html
```

![screen shot 2016-11-17 at 10 56 00 pm](https://cloud.githubusercontent.com/assets/34700/20419053/0fcc4012-ad19-11e6-977a-e2c38f8fa1f9.png)

Tested on: 

* Chrome (Version 54.0 )
* Safari 10.0.1

**Comment by njonsson** [comment] 2016-11-18 16:03
I am using ExDoc v0.14.3.

**Comment by njonsson** [comment] 2016-11-18 16:09
I have more information on the potential source of the problem. My _mix.exs_ contains ExDoc options in the `def project do` block. When I remove these options, the generated docs have no JavaScript errors. Note that the referenced files, _README.md_, _License.md_, and _History.md_, all exist in the root of my project.

```elixir
docs: [extras: ["README.md":  [filename: "about",
                               title: "About my project"],
                "License.md": [filename: "license",
                               title: "Project license"],
                "History.md": [filename: "history",
                               title: "Project history"]]]
```

**Comment by josevalim** [comment] 2016-11-18 16:31
@njonsson could you please push a small project to github that reproduces the error? It would help us a lot on fixing it. :)

**Comment by josevalim** [comment] 2016-11-18 16:40
Nevermind, I can reproduce it on Elixir source: http://elixir-lang.org/docs/master/elixir/behaviours.html#full-list :)

**Comment by milmazz** [comment] 2016-11-18 17:05
@josevalim The issue is that we create first the extra pages... and then the `sidebar_items-<rev>.js`. So, when you create an extra page... `head_template.eex` returns `nil` :(

**Comment by milmazz** [comment] 2016-11-18 17:06
@josevalim Are you working on this?

**Comment by josevalim** [comment] 2016-11-18 17:11
@milmazz yes :)

**Comment by josevalim** [comment] 2016-11-18 17:48
Fixed in master. It also allowed us to remove the duplication between epub/html formatters in regards to extra handling.

**Closed** 2016-11-18 17:48 UTC
